// Generated by CoffeeScript 1.6.3
(function() {
  var fs, path, recursive;

  fs = require('fs');

  path = require('path');

  recursive = {
    file: function(dir, fn) {
      var file, _i, _len, _ref;
      _ref = fs.readdirSync(dir);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        if (fs.statSync(path.join(dir, file)).isDirectory()) {
          arguments.callee(path.join(dir, file), fn);
        } else {
          fn(file);
        }
      }
      return this;
    },
    dir: function(dir, fn) {
      var file, _i, _len, _ref;
      _ref = fs.readdirSync(dir);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        if (fs.statSync(path.join(dir, file)).isDirectory()) {
          fn(path.join(dir, file));
          arguments.callee(path.join(dir, file), fn);
        }
      }
      return this;
    }
  };

  module.exports = recursive;

}).call(this);
